import { DesignTokens } from "@/lib/tokens";

// ─── Variant types ────────────────────────────────────────────────────────────

export type ProjectVariants = {
  navbar: "default" | "centered" | "minimal";
  hero: "centered" | "split";
  pricing: "cards" | "compact" | "featured";
  features: "grid" | "icons" | "alternating";
  testimonials: "grid" | "featured" | "wall";
  cta: "centered" | "split" | "banner";
};

export type ProjectSections = {
  navbar?: boolean;
  hero?: boolean;
  features?: boolean;
  testimonials?: boolean;
  pricing?: boolean;
  cta?: boolean;
};

// ─── Token file ───────────────────────────────────────────────────────────────

function generateTokensTs(tokens: DesignTokens): string {
  const { colors: c, typography: t, radius: r, spacing: s, semantic: sem } = tokens;
  return `// Generated by HoltzUI — design token values for your project.
// CSS variables are defined in app/globals.css.
export const tokens = {
  colors: {
    primary:     { DEFAULT: "${c.primary.DEFAULT}",  foreground: "${c.primary.foreground}" },
    secondary:   { DEFAULT: "${c.secondary.DEFAULT}", foreground: "${c.secondary.foreground}" },
    accent:      { DEFAULT: "${c.accent.DEFAULT}",    foreground: "${c.accent.foreground}" },
    destructive: { DEFAULT: "${c.destructive.DEFAULT}", foreground: "${c.destructive.foreground}" },
    background:  "${c.background}",
    foreground:  "${c.foreground}",
    muted:       { DEFAULT: "${c.muted.DEFAULT}",     foreground: "${c.muted.foreground}" },
    card:        { DEFAULT: "${c.card.DEFAULT}",      foreground: "${c.card.foreground}" },
    border:      "${c.border}",
    input:       "${c.input}",
    ring:        "${c.ring}",
  },
  typography: {
    fontSans:     "${t.fontSans}",
    fontMono:     "${t.fontMono}",
    baseFontSize: "${t.baseFontSize}",
    lineHeight:   "${t.lineHeight}",
  },
  radius: { base: "${r.base}" },
  spacing: { base: "${s.base}" },
  semantic: {
    hero:         { background: "${sem.hero.background}",         text: "${sem.hero.text}",         button: "${sem.hero.button}" },
    navbar:       { background: "${sem.navbar.background}",       text: "${sem.navbar.text}",       border: "${sem.navbar.border}" },
    pricing:      { background: "${sem.pricing.background}",      text: "${sem.pricing.text}",      highlight: "${sem.pricing.highlight}" },
    features:     { background: "${sem.features.background}",     text: "${sem.features.text}" },
    testimonials: { background: "${sem.testimonials.background}", text: "${sem.testimonials.text}" },
    cta:          { background: "${sem.cta.background}",          text: "${sem.cta.text}",         buttonBackground: "${sem.cta.buttonBackground}", buttonText: "${sem.cta.buttonText}" },
  },
} as const;

export type Tokens = typeof tokens;
`;
}

// ─── Navbar components ────────────────────────────────────────────────────────

function navbarDefault(brandName: string): string {
  return `const navLinks = [
  { id: 1, name: "Features", href: "#features" },
  { id: 2, name: "Pricing",  href: "#pricing" },
  { id: 3, name: "Docs",     href: "#" },
  { id: 4, name: "Blog",     href: "#" },
];

interface NavbarProps { brandName?: string; }

export function Navbar({ brandName = "${brandName}" }: NavbarProps) {
  return (
    <nav
      style={{
        backgroundColor: "var(--navbar-background)",
        color: "var(--navbar-text)",
        borderBottom: "1px solid var(--navbar-border)",
      }}
      className="w-full"
    >
      <div className="relative max-w-7xl w-full flex md:grid md:grid-cols-12 items-center px-4 md:px-8 mx-auto py-7">
        <div className="md:col-span-3">
          <h1 className="text-2xl font-semibold">
            {brandName.slice(0, -2)}
            <span style={{ color: "var(--primary)" }}>{brandName.slice(-2)}</span>
          </h1>
        </div>
        <div className="hidden md:flex justify-center items-center col-span-6 gap-x-2">
          {navLinks.map((item) => (
            <a
              key={item.id}
              href={item.href}
              style={{ color: "var(--muted-foreground)" }}
              className="hover:opacity-80 transition-opacity px-4 py-2 rounded-md text-sm font-medium"
            >
              {item.name}
            </a>
          ))}
        </div>
        <div className="flex items-center gap-x-2 ms-auto md:col-span-3">
          <button
            style={{ backgroundColor: "var(--primary)", color: "var(--primary-foreground)", borderRadius: "var(--radius)" }}
            className="px-4 py-2 text-sm font-medium hover:opacity-90 transition-opacity"
          >
            Login
          </button>
          <button
            style={{ backgroundColor: "var(--secondary)", color: "var(--secondary-foreground)", borderRadius: "var(--radius)" }}
            className="px-4 py-2 text-sm font-medium hover:opacity-90 transition-opacity"
          >
            Register
          </button>
        </div>
      </div>
    </nav>
  );
}
`;
}

function navbarCentered(brandName: string): string {
  return `const navLinks = [
  { id: 1, name: "Features", href: "#features" },
  { id: 2, name: "Pricing",  href: "#pricing" },
  { id: 3, name: "Docs",     href: "#" },
  { id: 4, name: "Blog",     href: "#" },
];

interface NavbarProps { brandName?: string; }

export function Navbar({ brandName = "${brandName}" }: NavbarProps) {
  return (
    <nav
      style={{
        backgroundColor: "var(--navbar-background)",
        color: "var(--navbar-text)",
        borderBottom: "1px solid var(--navbar-border)",
      }}
      className="w-full"
    >
      <div className="max-w-7xl mx-auto px-6 py-5 flex flex-col items-center gap-4">
        <h1 className="text-2xl font-semibold">
          {brandName.slice(0, -2)}
          <span style={{ color: "var(--primary)" }}>{brandName.slice(-2)}</span>
        </h1>
        <div className="flex gap-6">
          {navLinks.map((item) => (
            <a
              key={item.id}
              href={item.href}
              style={{ color: "var(--muted-foreground)" }}
              className="hover:opacity-80 transition-opacity text-sm font-medium"
            >
              {item.name}
            </a>
          ))}
        </div>
      </div>
    </nav>
  );
}
`;
}

function navbarMinimal(brandName: string): string {
  return `interface NavbarProps { brandName?: string; }

export function Navbar({ brandName = "${brandName}" }: NavbarProps) {
  return (
    <nav
      style={{
        backgroundColor: "var(--navbar-background)",
        color: "var(--navbar-text)",
        borderBottom: "1px solid var(--navbar-border)",
      }}
      className="w-full"
    >
      <div className="max-w-7xl mx-auto px-6 py-4 flex justify-between items-center">
        <h1 className="text-xl font-bold tracking-tight">
          {brandName.slice(0, -2)}
          <span style={{ color: "var(--primary)" }}>{brandName.slice(-2)}</span>
        </h1>
        <button
          style={{ backgroundColor: "var(--primary)", color: "var(--primary-foreground)", borderRadius: "var(--radius)" }}
          className="px-5 py-2 text-sm font-medium hover:opacity-90 transition-opacity"
        >
          Get Started
        </button>
      </div>
    </nav>
  );
}
`;
}

function generateNavbarComponent(variant: ProjectVariants["navbar"], brandName: string): string {
  switch (variant) {
    case "centered": return navbarCentered(brandName);
    case "minimal":  return navbarMinimal(brandName);
    default:         return navbarDefault(brandName);
  }
}

// ─── Hero components ──────────────────────────────────────────────────────────

function heroCentered(brandName: string): string {
  return `interface HeroProps {
  brandName?: string;
  headline?: string;
  subheadline?: string;
  ctaLabel?: string;
}

export function Hero({
  brandName = "${brandName}",
  headline,
  subheadline = "A complete UI system generated from your design tokens.",
  ctaLabel = "Get Started",
}: HeroProps) {
  const resolvedHeadline = headline ?? \`Build faster with \${brandName}\`;
  return (
    <section
      style={{ backgroundColor: "var(--hero-background)", color: "var(--hero-text)" }}
      className="w-full py-24 px-6"
    >
      <div className="max-w-4xl mx-auto flex flex-col items-center text-center gap-y-6">
        <h1 className="text-5xl font-bold leading-tight tracking-tight">
          {resolvedHeadline}
        </h1>
        <p className="text-xl max-w-2xl" style={{ opacity: 0.7 }}>
          {subheadline}
        </p>
        <button
          style={{ backgroundColor: "var(--hero-button)", color: "var(--primary-foreground)", borderRadius: "var(--radius)" }}
          className="px-6 py-3 text-base font-medium hover:opacity-90 transition-opacity"
        >
          {ctaLabel}
        </button>
      </div>
    </section>
  );
}
`;
}

function heroSplit(brandName: string): string {
  return `interface HeroProps {
  brandName?: string;
  headline?: string;
  subheadline?: string;
  ctaLabel?: string;
}

export function Hero({
  brandName = "${brandName}",
  headline,
  subheadline = "Generate full UI systems instantly.",
  ctaLabel = "Get Started",
}: HeroProps) {
  const resolvedHeadline = headline ?? \`Build faster with \${brandName}\`;
  return (
    <section
      style={{ backgroundColor: "var(--hero-background)", color: "var(--hero-text)" }}
      className="py-24 px-6"
    >
      <div className="max-w-6xl mx-auto grid md:grid-cols-2 gap-12 items-center">
        <div>
          <h1 className="text-5xl font-bold leading-tight tracking-tight mb-6">
            {resolvedHeadline}
          </h1>
          <p className="text-xl mb-8" style={{ opacity: 0.7 }}>
            {subheadline}
          </p>
          <button
            style={{ backgroundColor: "var(--hero-button)", color: "var(--primary-foreground)", borderRadius: "var(--radius)" }}
            className="px-6 py-3 text-base font-medium hover:opacity-90 transition-opacity"
          >
            {ctaLabel}
          </button>
        </div>
        <div
          className="w-full h-80 rounded-[var(--radius)]"
          style={{ backgroundColor: "var(--muted)" }}
        />
      </div>
    </section>
  );
}
`;
}

function generateHeroComponent(variant: ProjectVariants["hero"], brandName: string): string {
  return variant === "split" ? heroSplit(brandName) : heroCentered(brandName);
}

// ─── Features components ──────────────────────────────────────────────────────

function featuresGrid(): string {
  return `export function Features() {
  return (
    <section
      style={{ backgroundColor: "var(--features-background)", color: "var(--features-text)" }}
      className="py-24 px-6"
    >
      <div className="max-w-6xl mx-auto text-center mb-16">
        <h2 className="text-3xl font-bold">Everything you need to build faster</h2>
        <p className="mt-4" style={{ opacity: 0.6 }}>Powerful features to help you ship quickly</p>
      </div>
      <div className="max-w-6xl mx-auto grid md:grid-cols-3 gap-8">
        {["Fast Setup", "Custom Branding", "Export Ready"].map((title) => (
          <div
            key={title}
            style={{ backgroundColor: "var(--card)", color: "var(--card-foreground)", border: "1px solid var(--border)", borderRadius: "var(--radius)" }}
            className="p-6"
          >
            <h3 className="font-semibold mb-2">{title}</h3>
            <p className="text-sm" style={{ opacity: 0.6 }}>Your feature description goes here.</p>
          </div>
        ))}
      </div>
    </section>
  );
}
`;
}

function featuresIcons(): string {
  return `const features = [
  { title: "Fast Setup",       description: "Get started in minutes with prebuilt UI blocks tailored to your brand.",               icon: "\u26a1" },
  { title: "Custom Branding",  description: "Apply your brand colors, fonts, and radius across every component instantly.",        icon: "\ud83c\udfa8" },
  { title: "Export Ready",     description: "Copy clean Tailwind code and drop it straight into your project.",                    icon: "\ud83d\udce6" },
  { title: "Token System",     description: "A semantic design token layer keeps every section consistent automatically.",          icon: "\ud83d\udd17" },
  { title: "Live Preview",     description: "See changes rendered in real time as you adjust your brand settings.",                 icon: "\ud83d\udc41" },
  { title: "Multiple Layouts", description: "Mix and match section variants to find the layout that fits your brand.",             icon: "\ud83e\udde9" },
];

export function Features() {
  return (
    <section
      style={{ backgroundColor: "var(--features-background)", color: "var(--features-text)" }}
      className="py-24 px-6"
    >
      <div className="max-w-6xl mx-auto text-center mb-16">
        <h2 className="text-3xl font-bold">Built for speed. Designed for scale.</h2>
        <p className="mt-4 max-w-xl mx-auto" style={{ opacity: 0.6 }}>Everything your team needs to ship polished UIs without starting from scratch.</p>
      </div>
      <div className="max-w-6xl mx-auto grid md:grid-cols-3 gap-6">
        {features.map((f) => (
          <div
            key={f.title}
            style={{ backgroundColor: "var(--card)", color: "var(--card-foreground)", border: "1px solid var(--border)", borderRadius: "var(--radius)" }}
            className="p-8 flex flex-col gap-4"
          >
            <div
              className="w-12 h-12 flex items-center justify-center text-xl font-bold"
              style={{ backgroundColor: "var(--primary)", color: "var(--primary-foreground)", borderRadius: "var(--radius)" }}
            >
              {f.icon}
            </div>
            <h3 className="font-semibold text-lg">{f.title}</h3>
            <p className="text-sm leading-relaxed" style={{ opacity: 0.6 }}>{f.description}</p>
          </div>
        ))}
      </div>
    </section>
  );
}
`;
}

function featuresAlternating(): string {
  return `const steps = [
  { badge: "01", title: "Set up your brand in minutes", description: "Configure your color palette, typography, and spacing using a visual token system — no config files, no guessing." },
  { badge: "02", title: "Preview every component live",  description: "See exactly how your brand looks across navbars, heroes, pricing, and feature sections as you tweak each token." },
  { badge: "03", title: "Copy Tailwind code instantly",  description: "Every section exports clean, production-ready Tailwind v4 JSX. Paste it, ship it, done." },
];

export function Features() {
  return (
    <section
      style={{ backgroundColor: "var(--features-background)", color: "var(--features-text)" }}
      className="py-24 px-6"
    >
      <div className="max-w-5xl mx-auto text-center mb-20">
        <h2 className="text-3xl font-bold">How it works</h2>
        <p className="mt-4 max-w-xl mx-auto" style={{ opacity: 0.6 }}>A simple three-step process from idea to production-ready UI.</p>
      </div>
      <div className="max-w-5xl mx-auto flex flex-col gap-20">
        {steps.map((item, i) => (
          <div
            key={item.badge}
            className={\`flex flex-col md:flex-row items-center gap-12 \${i % 2 === 1 ? "md:flex-row-reverse" : ""}\`}
          >
            <div
              className="flex-1 min-h-[220px] rounded-[var(--radius)] flex items-center justify-center"
              style={{ backgroundColor: "var(--secondary)", color: "var(--secondary-foreground)" }}
            >
              <span className="text-7xl font-black" style={{ opacity: 0.3 }}>{item.badge}</span>
            </div>
            <div className="flex-1 flex flex-col gap-4">
              <div className="text-xs font-semibold tracking-widest uppercase" style={{ color: "var(--primary)" }}>Step {item.badge}</div>
              <h3 className="text-2xl font-bold">{item.title}</h3>
              <p style={{ opacity: 0.6 }} className="leading-relaxed">{item.description}</p>
              <button
                className="self-start mt-2 px-5 py-2.5 text-sm font-medium hover:opacity-90 transition-opacity rounded-[var(--radius)]"
                style={{ backgroundColor: "var(--primary)", color: "var(--primary-foreground)" }}
              >
                Learn more
              </button>
            </div>
          </div>
        ))}
      </div>
    </section>
  );
}
`;
}

function generateFeaturesComponent(variant: ProjectVariants["features"]): string {
  switch (variant) {
    case "icons":       return featuresIcons();
    case "alternating": return featuresAlternating();
    default:            return featuresGrid();
  }
}

// ─── Testimonials components ──────────────────────────────────────────────────

const testimonialsData = `const testimonials = [
  { quote: "This saved me hours of UI work. I can ship landing pages instantly.",   author: "Alex R.",    role: "Indie Developer",  initials: "AR" },
  { quote: "The token system makes branding so fast and consistent.",               author: "Jamie L.",   role: "Product Designer", initials: "JL" },
  { quote: "I use this for all my client mockups now. Nothing else comes close.",   author: "Sam T.",    role: "Freelancer",       initials: "ST" },
  { quote: "Went from blank canvas to polished landing page in under an hour.",     author: "Morgan K.", role: "Startup Founder",  initials: "MK" },
  { quote: "The presets alone are worth it. My team ships twice as fast.",          author: "Dana W.",   role: "Engineering Lead", initials: "DW" },
  { quote: "Clean exports, real Tailwind code. No cleanup needed.",                 author: "Riley P.",  role: "Full-Stack Dev",   initials: "RP" },
];
`;

function testimonialsGrid(): string {
  return `${testimonialsData}
export function Testimonials() {
  return (
    <section
      style={{ backgroundColor: "var(--testimonials-background)", color: "var(--testimonials-text)" }}
      className="py-24 px-6"
    >
      <div className="max-w-6xl mx-auto text-center mb-16">
        <h2 className="text-3xl font-bold">Loved by developers &amp; creators</h2>
        <p className="mt-4" style={{ opacity: 0.6 }}>People use this to build faster and ship more</p>
      </div>
      <div className="max-w-6xl mx-auto grid md:grid-cols-3 gap-8">
        {testimonials.slice(0, 3).map((t) => (
          <div
            key={t.author}
            style={{ backgroundColor: "var(--card)", color: "var(--card-foreground)", border: "1px solid var(--border)", borderRadius: "var(--radius)" }}
            className="p-6 flex flex-col gap-4"
          >
            <p className="text-sm leading-relaxed flex-1">&ldquo;{t.quote}&rdquo;</p>
            <span className="text-xs font-medium" style={{ color: "var(--primary)" }}>&mdash; {t.author}</span>
          </div>
        ))}
      </div>
    </section>
  );
}
`;
}

function testimonialsFeatured(): string {
  return `${testimonialsData}
export function Testimonials() {
  const [featured, ...rest] = testimonials;
  return (
    <section
      style={{ backgroundColor: "var(--testimonials-background)", color: "var(--testimonials-text)" }}
      className="py-24 px-6"
    >
      <div className="max-w-6xl mx-auto text-center mb-16">
        <h2 className="text-3xl font-bold">What people are saying</h2>
        <p className="mt-4" style={{ opacity: 0.6 }}>Join thousands of developers and designers who ship faster</p>
      </div>
      <div className="max-w-3xl mx-auto mb-12">
        <div
          className="p-10 rounded-[var(--radius)] text-center flex flex-col items-center gap-6"
          style={{ backgroundColor: "var(--primary)", color: "var(--primary-foreground)" }}
        >
          <p className="text-xl font-medium leading-relaxed">&ldquo;{featured.quote}&rdquo;</p>
          <div className="flex flex-col items-center gap-1">
            <div
              className="w-10 h-10 rounded-full flex items-center justify-center text-sm font-bold"
              style={{ backgroundColor: "var(--primary-foreground)", color: "var(--primary)" }}
            >
              {featured.initials}
            </div>
            <span className="text-sm font-semibold">{featured.author}</span>
            <span className="text-xs" style={{ opacity: 0.7 }}>{featured.role}</span>
          </div>
        </div>
      </div>
      <div className="max-w-6xl mx-auto grid md:grid-cols-5 gap-4">
        {rest.map((t) => (
          <div
            key={t.author}
            style={{ backgroundColor: "var(--card)", color: "var(--card-foreground)", border: "1px solid var(--border)", borderRadius: "var(--radius)" }}
            className="p-5 flex flex-col gap-3"
          >
            <p className="text-xs leading-relaxed flex-1" style={{ opacity: 0.8 }}>&ldquo;{t.quote}&rdquo;</p>
            <div className="flex items-center gap-2">
              <div
                className="w-6 h-6 rounded-full flex items-center justify-center text-xs font-bold flex-shrink-0"
                style={{ backgroundColor: "var(--primary)", color: "var(--primary-foreground)" }}
              >
                {t.initials}
              </div>
              <div>
                <p className="text-xs font-medium leading-none">{t.author}</p>
                <p className="text-xs mt-0.5" style={{ opacity: 0.5 }}>{t.role}</p>
              </div>
            </div>
          </div>
        ))}
      </div>
    </section>
  );
}
`;
}

function testimonialsWall(): string {
  return `${testimonialsData}
export function Testimonials() {
  const cols = [testimonials.slice(0, 2), testimonials.slice(2, 4), testimonials.slice(4, 6)];
  return (
    <section
      style={{ backgroundColor: "var(--testimonials-background)", color: "var(--testimonials-text)" }}
      className="py-24 px-6"
    >
      <div className="max-w-6xl mx-auto text-center mb-16">
        <h2 className="text-3xl font-bold">Loved by developers &amp; creators</h2>
        <p className="mt-4" style={{ opacity: 0.6 }}>People use this to build faster and ship more</p>
      </div>
      <div className="max-w-6xl mx-auto grid md:grid-cols-3 gap-6 items-start">
        {cols.map((col, ci) => (
          <div key={ci} className={\`flex flex-col gap-6 \${ci === 1 ? "md:mt-8" : ""}\`}>
            {col.map((t) => (
              <div
                key={t.author}
                style={{ backgroundColor: "var(--card)", color: "var(--card-foreground)", border: "1px solid var(--border)", borderRadius: "var(--radius)" }}
                className="p-6 flex flex-col gap-4"
              >
                <div className="flex gap-0.5">
                  {[...Array(5)].map((_, i) => (
                    <span key={i} style={{ color: "var(--primary)" }}>\u2605</span>
                  ))}
                </div>
                <p className="text-sm leading-relaxed flex-1">&ldquo;{t.quote}&rdquo;</p>
                <div className="flex items-center gap-3">
                  <div
                    className="w-8 h-8 rounded-full flex items-center justify-center text-xs font-bold flex-shrink-0"
                    style={{ backgroundColor: "var(--primary)", color: "var(--primary-foreground)" }}
                  >
                    {t.initials}
                  </div>
                  <div>
                    <p className="text-sm font-medium leading-none">{t.author}</p>
                    <p className="text-xs mt-0.5" style={{ opacity: 0.5 }}>{t.role}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        ))}
      </div>
    </section>
  );
}
`;
}

function generateTestimonialsComponent(variant: ProjectVariants["testimonials"]): string {
  switch (variant) {
    case "featured": return testimonialsFeatured();
    case "wall":     return testimonialsWall();
    default:         return testimonialsGrid();
  }
}

// ─── Pricing components ───────────────────────────────────────────────────────

function pricingCards(): string {
  return `export function Pricing() {
  return (
    <section
      style={{ backgroundColor: "var(--pricing-background)", color: "var(--pricing-text)" }}
      className="py-24 px-6"
    >
      <div className="max-w-6xl mx-auto text-center mb-12">
        <h2 className="text-3xl font-bold">Simple, transparent pricing</h2>
        <p className="mt-4" style={{ opacity: 0.7 }}>Choose the plan that fits your needs</p>
      </div>
      <div className="max-w-6xl mx-auto grid md:grid-cols-3 gap-8">
        <div style={{ backgroundColor: "var(--card)", color: "var(--card-foreground)", border: "1px solid var(--border)", borderRadius: "var(--radius)" }} className="p-6">
          <h3 className="text-xl font-semibold mb-2">Starter</h3>
          <p className="mb-4" style={{ opacity: 0.7 }}>$9/mo</p>
          <button style={{ backgroundColor: "var(--secondary)", color: "var(--secondary-foreground)", borderRadius: "var(--radius)" }} className="w-full py-2 text-sm font-medium hover:opacity-90 transition-opacity">Choose Plan</button>
        </div>
        <div style={{ backgroundColor: "var(--card)", color: "var(--card-foreground)", border: "2px solid var(--pricing-highlight)", borderRadius: "var(--radius)" }} className="p-6">
          <h3 className="text-xl font-semibold mb-2">Pro</h3>
          <p className="mb-4" style={{ opacity: 0.7 }}>$29/mo</p>
          <button style={{ backgroundColor: "var(--primary)", color: "var(--primary-foreground)", borderRadius: "var(--radius)" }} className="w-full py-2 text-sm font-medium hover:opacity-90 transition-opacity">Get Started</button>
        </div>
        <div style={{ backgroundColor: "var(--card)", color: "var(--card-foreground)", border: "1px solid var(--border)", borderRadius: "var(--radius)" }} className="p-6">
          <h3 className="text-xl font-semibold mb-2">Enterprise</h3>
          <p className="mb-4" style={{ opacity: 0.7 }}>Custom</p>
          <button style={{ backgroundColor: "var(--secondary)", color: "var(--secondary-foreground)", borderRadius: "var(--radius)" }} className="w-full py-2 text-sm font-medium hover:opacity-90 transition-opacity">Contact Us</button>
        </div>
      </div>
    </section>
  );
}
`;
}

function pricingCompact(): string {
  return `const plans = [
  { name: "Starter",    price: "$9",     period: "/mo", desc: "Perfect for side projects", cta: "Choose Plan",  primary: false },
  { name: "Pro",        price: "$29",    period: "/mo", desc: "For growing teams",          cta: "Get Started",  primary: true  },
  { name: "Enterprise", price: "Custom", period: "",    desc: "Unlimited scale",             cta: "Contact Us",   primary: false },
];

export function Pricing() {
  return (
    <section
      style={{ backgroundColor: "var(--pricing-background)", color: "var(--pricing-text)" }}
      className="py-24 px-6"
    >
      <div className="max-w-3xl mx-auto">
        <div className="text-center mb-12">
          <h2 className="text-3xl font-bold">Simple, transparent pricing</h2>
          <p className="mt-4" style={{ opacity: 0.7 }}>Choose the plan that fits your needs</p>
        </div>
        <div style={{ border: "1px solid var(--border)", borderRadius: "var(--radius)" }} className="flex flex-col divide-y overflow-hidden">
          {plans.map((plan) => (
            <div
              key={plan.name}
              className="flex items-center justify-between px-6 py-5"
              style={{ backgroundColor: "var(--card)", color: "var(--card-foreground)" }}
            >
              <div>
                <p className="font-semibold">{plan.name}</p>
                <p className="text-sm" style={{ opacity: 0.6 }}>{plan.desc}</p>
              </div>
              <div className="flex items-center gap-6">
                <span className="text-xl font-bold">
                  {plan.price}<span className="text-sm font-normal" style={{ opacity: 0.6 }}>{plan.period}</span>
                </span>
                <button
                  className="px-4 py-2 text-sm font-medium whitespace-nowrap hover:opacity-90 transition-opacity"
                  style={plan.primary
                    ? { backgroundColor: "var(--primary)",   color: "var(--primary-foreground)",   borderRadius: "var(--radius)" }
                    : { backgroundColor: "var(--secondary)", color: "var(--secondary-foreground)", borderRadius: "var(--radius)" }}
                >
                  {plan.cta}
                </button>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
`;
}

function pricingFeatured(): string {
  return `export function Pricing() {
  return (
    <section
      style={{ backgroundColor: "var(--pricing-background)", color: "var(--pricing-text)" }}
      className="py-24 px-6"
    >
      <div className="max-w-6xl mx-auto">
        <div className="text-center mb-12">
          <h2 className="text-3xl font-bold">Simple, transparent pricing</h2>
          <p className="mt-4" style={{ opacity: 0.7 }}>Choose the plan that fits your needs</p>
        </div>
        <div className="grid md:grid-cols-3 gap-6 items-stretch">
          <div className="flex flex-col justify-between p-6 rounded-[var(--radius)] border" style={{ borderColor: "var(--border)", backgroundColor: "var(--card)", color: "var(--card-foreground)" }}>
            <div>
              <p className="text-sm font-semibold uppercase tracking-widest" style={{ opacity: 0.5 }}>Starter</p>
              <p className="text-3xl font-bold mt-2">$9<span className="text-base font-normal" style={{ opacity: 0.6 }}>/mo</span></p>
              <p className="text-sm mt-3" style={{ opacity: 0.6 }}>Perfect for side projects and small teams.</p>
            </div>
            <button className="mt-8 w-full py-2.5 text-sm font-medium hover:opacity-90 transition-opacity rounded-[var(--radius)]" style={{ backgroundColor: "var(--secondary)", color: "var(--secondary-foreground)" }}>Choose Plan</button>
          </div>
          <div className="flex flex-col justify-between p-8 rounded-[var(--radius)] shadow-lg -mt-4 -mb-4" style={{ backgroundColor: "var(--primary)", color: "var(--primary-foreground)" }}>
            <div>
              <p className="text-sm font-semibold uppercase tracking-widest" style={{ opacity: 0.7 }}>Pro</p>
              <p className="text-4xl font-bold mt-2">$29<span className="text-base font-normal" style={{ opacity: 0.7 }}>/mo</span></p>
              <p className="text-sm mt-3" style={{ opacity: 0.8 }}>Everything you need to ship fast and scale.</p>
              <ul className="mt-6 space-y-2 text-sm" style={{ opacity: 0.85 }}>
                <li>\u2713 Unlimited projects</li>
                <li>\u2713 Priority support</li>
                <li>\u2713 Advanced analytics</li>
              </ul>
            </div>
            <button className="mt-8 w-full py-2.5 text-sm font-medium hover:opacity-90 transition-opacity rounded-[var(--radius)]" style={{ backgroundColor: "var(--primary-foreground)", color: "var(--primary)" }}>Get Started</button>
          </div>
          <div className="flex flex-col justify-between p-6 rounded-[var(--radius)] border" style={{ borderColor: "var(--border)", backgroundColor: "var(--card)", color: "var(--card-foreground)" }}>
            <div>
              <p className="text-sm font-semibold uppercase tracking-widest" style={{ opacity: 0.5 }}>Enterprise</p>
              <p className="text-3xl font-bold mt-2">Custom</p>
              <p className="text-sm mt-3" style={{ opacity: 0.6 }}>Dedicated support, SLAs, and unlimited scale.</p>
            </div>
            <button className="mt-8 w-full py-2.5 text-sm font-medium hover:opacity-90 transition-opacity rounded-[var(--radius)]" style={{ backgroundColor: "var(--secondary)", color: "var(--secondary-foreground)" }}>Contact Us</button>
          </div>
        </div>
      </div>
    </section>
  );
}
`;
}

function generatePricingComponent(variant: ProjectVariants["pricing"]): string {
  switch (variant) {
    case "compact":  return pricingCompact();
    case "featured": return pricingFeatured();
    default:         return pricingCards();
  }
}

// ─── CTA components ───────────────────────────────────────────────────────────

function ctaCentered(): string {
  return `interface CTAProps { heading?: string; subheading?: string; ctaLabel?: string; }

export function CTA({
  heading    = "Ready to build your own UI system?",
  subheading = "Generate, customize, and export production-ready UI in seconds.",
  ctaLabel   = "Get Started",
}: CTAProps) {
  return (
    <section
      style={{ backgroundColor: "var(--cta-background)", color: "var(--cta-text)" }}
      className="py-24 px-6"
    >
      <div className="max-w-4xl mx-auto text-center">
        <h2 className="text-3xl font-bold mb-4">{heading}</h2>
        <p className="mb-8" style={{ opacity: 0.8 }}>{subheading}</p>
        <button
          style={{ backgroundColor: "var(--cta-button-background)", color: "var(--cta-button-text)", borderRadius: "var(--radius)" }}
          className="px-6 py-3 font-medium hover:opacity-90 transition"
        >
          {ctaLabel}
        </button>
      </div>
    </section>
  );
}
`;
}

function ctaSplit(): string {
  return `interface CTAProps { heading?: string; subheading?: string; ctaLabel?: string; }

export function CTA({
  heading    = "Ready to build your own UI system?",
  subheading = "Generate, customize, and export production-ready UI in seconds. No design experience required.",
  ctaLabel   = "Get Started Free",
}: CTAProps) {
  return (
    <section
      style={{ backgroundColor: "var(--cta-background)", color: "var(--cta-text)" }}
      className="py-24 px-6"
    >
      <div className="max-w-6xl mx-auto flex flex-col md:flex-row items-center justify-between gap-12">
        <div className="flex-1">
          <h2 className="text-3xl font-bold mb-4">{heading}</h2>
          <p className="max-w-md leading-relaxed" style={{ opacity: 0.8 }}>{subheading}</p>
        </div>
        <div className="flex flex-col gap-3 items-start md:items-end flex-shrink-0">
          <button
            style={{ backgroundColor: "var(--cta-button-background)", color: "var(--cta-button-text)", borderRadius: "var(--radius)" }}
            className="px-8 py-3 font-medium hover:opacity-90 transition"
          >
            {ctaLabel}
          </button>
          <span className="text-sm" style={{ opacity: 0.6 }}>No credit card required</span>
        </div>
      </div>
    </section>
  );
}
`;
}

function ctaBanner(): string {
  return `interface CTAProps { heading?: string; ctaLabel?: string; }

export function CTA({
  heading  = "Start building your brand system today",
  ctaLabel = "Get Started",
}: CTAProps) {
  return (
    <section
      style={{ backgroundColor: "var(--cta-background)", color: "var(--cta-text)" }}
      className="py-6 px-6"
    >
      <div className="max-w-6xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-4">
        <p className="font-medium text-lg" style={{ opacity: 0.9 }}>
          {heading} &mdash;&nbsp;
          <span className="font-normal text-base" style={{ opacity: 0.6 }}>free forever for solo builders.</span>
        </p>
        <button
          style={{ backgroundColor: "var(--cta-button-background)", color: "var(--cta-button-text)", borderRadius: "var(--radius)" }}
          className="flex-shrink-0 px-6 py-2.5 font-medium text-sm hover:opacity-90 transition"
        >
          {ctaLabel}
        </button>
      </div>
    </section>
  );
}
`;
}

function generateCTAComponent(variant: ProjectVariants["cta"]): string {
  switch (variant) {
    case "split":  return ctaSplit();
    case "banner": return ctaBanner();
    default:       return ctaCentered();
  }
}

// ─── CSS + Layout ─────────────────────────────────────────────────────────────

export function generateGlobalsCss(tokens: DesignTokens): string {
  const { colors: c, radius: r, typography: t, spacing: s, semantic: sem } = tokens;
  return `@import "tailwindcss";
@import "tw-animate-css";

@custom-variant dark (&:is(.dark *));

@theme inline {
  --color-background:               var(--background);
  --color-foreground:               var(--foreground);
  --color-card:                     var(--card);
  --color-card-foreground:          var(--card-foreground);
  --color-primary:                  var(--primary);
  --color-primary-foreground:       var(--primary-foreground);
  --color-secondary:                var(--secondary);
  --color-secondary-foreground:     var(--secondary-foreground);
  --color-muted:                    var(--muted);
  --color-muted-foreground:         var(--muted-foreground);
  --color-accent:                   var(--accent);
  --color-accent-foreground:        var(--accent-foreground);
  --color-destructive:              var(--destructive);
  --color-border:                   var(--border);
  --color-input:                    var(--input);
  --color-ring:                     var(--ring);
  --radius-sm:                      calc(var(--radius) * 0.6);
  --radius-md:                      calc(var(--radius) * 0.8);
  --radius-lg:                      var(--radius);
}

:root {
  --background:               ${c.background};
  --foreground:               ${c.foreground};
  --card:                     ${c.card.DEFAULT};
  --card-foreground:          ${c.card.foreground};
  --primary:                  ${c.primary.DEFAULT};
  --primary-foreground:       ${c.primary.foreground};
  --secondary:                ${c.secondary.DEFAULT};
  --secondary-foreground:     ${c.secondary.foreground};
  --muted:                    ${c.muted.DEFAULT};
  --muted-foreground:         ${c.muted.foreground};
  --accent:                   ${c.accent.DEFAULT};
  --accent-foreground:        ${c.accent.foreground};
  --destructive:              ${c.destructive.DEFAULT};
  --border:                   ${c.border};
  --input:                    ${c.input};
  --ring:                     ${c.ring};
  --radius:                   ${r.base};
  --font-sans:                ${t.fontSans};
  --font-mono:                ${t.fontMono};
  --spacing-base:             ${s.base};

  /* Semantic tokens */
  --hero-background:          ${sem.hero.background};
  --hero-text:                ${sem.hero.text};
  --hero-button:              ${sem.hero.button};
  --navbar-background:        ${sem.navbar.background};
  --navbar-text:              ${sem.navbar.text};
  --navbar-border:            ${sem.navbar.border};
  --pricing-background:       ${sem.pricing.background};
  --pricing-text:             ${sem.pricing.text};
  --pricing-highlight:        ${sem.pricing.highlight};
  --features-background:      ${sem.features.background};
  --features-text:            ${sem.features.text};
  --testimonials-background:  ${sem.testimonials.background};
  --testimonials-text:        ${sem.testimonials.text};
  --cta-background:           ${sem.cta.background};
  --cta-text:                 ${sem.cta.text};
  --cta-button-background:    ${sem.cta.buttonBackground};
  --cta-button-text:          ${sem.cta.buttonText};
}

* {
  border-color: var(--border);
  outline-color: var(--ring);
}

body {
  background-color: var(--background);
  color: var(--foreground);
  font-family: var(--font-sans);
  font-size: ${t.baseFontSize};
  line-height: ${t.lineHeight};
}
`;
}

function generateLayoutTsx(tokens: DesignTokens): string {
  const fontFamily = tokens.typography.fontSans.split(",")[0].trim().replace(/['"]/g, "");
  const isGoogleFont = !fontFamily.startsWith("var(") && !fontFamily.startsWith("ui-");
  const fontImport = isGoogleFont
    ? `import { ${fontFamily.replace(/\s+/g, "_")} } from "next/font/google";\n\nconst font = ${fontFamily.replace(/\s+/g, "_")}({ subsets: ["latin"], weight: ["400", "600", "700"] });\n`
    : "";
  const className = isGoogleFont ? ' className={font.className}' : "";

  return `import type { Metadata } from "next";
import "./globals.css";
${fontImport}
export const metadata: Metadata = {
  title: "My App",
  description: "Generated by HoltzUI",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body${className}>{children}</body>
    </html>
  );
}
`;
}

function generatePackageJson(brandName: string): string {
  return JSON.stringify(
    {
      name: brandName.toLowerCase().replace(/\s+/g, "-"),
      version: "0.1.0",
      private: true,
      scripts: {
        dev: "next dev",
        build: "next build",
        start: "next start",
        lint: "eslint",
      },
      dependencies: {
        next: "16.2.4",
        react: "19.2.4",
        "react-dom": "19.2.4",
        "tailwind-merge": "^3.5.0",
        "tw-animate-css": "^1.4.0",
        clsx: "^2.1.1",
      },
      devDependencies: {
        "@tailwindcss/postcss": "^4",
        "@types/node": "^20",
        "@types/react": "^19",
        "@types/react-dom": "^19",
        typescript: "^5",
      },
    },
    null,
    2,
  );
}

function generateNextConfig(): string {
  return `import type { NextConfig } from "next";

const nextConfig: NextConfig = {};

export default nextConfig;
`;
}

function generatePostcssConfig(): string {
  return `export default {
  plugins: {
    "@tailwindcss/postcss": {},
  },
};
`;
}

function generateTsConfig(): string {
  return JSON.stringify(
    {
      compilerOptions: {
        target: "ES2017",
        lib: ["dom", "dom.iterable", "esnext"],
        allowJs: true,
        skipLibCheck: true,
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        module: "esnext",
        moduleResolution: "bundler",
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: "preserve",
        incremental: true,
        paths: { "@/*": ["./*"] },
      },
      include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
      exclude: ["node_modules"],
    },
    null,
    2,
  );
}

// ─── page.tsx generator ──────────────────────────────────────────────────────

function generatePageTsx(
  sections: ProjectSections,
  variants: ProjectVariants,
  brandName: string,
  heroContent?: { headline?: string; subheadline?: string; ctaLabel?: string },
  ctaContent?:  { heading?: string;  subheading?: string;  ctaLabel?: string },
): string {
  const imports: string[] = [];
  const usages: string[] = [];

  if (sections.navbar) {
    imports.push(`import { Navbar }       from "@/components/sections/Navbar";`);
    usages.push(`      <Navbar brandName="${brandName}" />`);
  }
  if (sections.hero) {
    imports.push(`import { Hero }         from "@/components/sections/Hero";`);
    const heroParts = [`brandName="${brandName}"`];
    if (heroContent?.headline)    heroParts.push(`headline="${heroContent.headline}"`);
    if (heroContent?.subheadline) heroParts.push(`subheadline="${heroContent.subheadline}"`);
    if (heroContent?.ctaLabel)    heroParts.push(`ctaLabel="${heroContent.ctaLabel}"`);
    usages.push(`      <Hero ${heroParts.join(" ")} />`);
  }
  if (sections.features) {
    imports.push(`import { Features }     from "@/components/sections/Features";`);
    usages.push(`      <Features />`);
  }
  if (sections.testimonials) {
    imports.push(`import { Testimonials } from "@/components/sections/Testimonials";`);
    usages.push(`      <Testimonials />`);
  }
  if (sections.pricing) {
    imports.push(`import { Pricing }      from "@/components/sections/Pricing";`);
    usages.push(`      <Pricing />`);
  }
  if (sections.cta) {
    imports.push(`import { CTA }          from "@/components/sections/CTA";`);
    const ctaParts: string[] = [];
    if (ctaContent?.heading)    ctaParts.push(`heading="${ctaContent.heading}"`);
    if (ctaContent?.subheading) ctaParts.push(`subheading="${ctaContent.subheading}"`);
    if (ctaContent?.ctaLabel)   ctaParts.push(`ctaLabel="${ctaContent.ctaLabel}"`);
    usages.push(ctaParts.length ? `      <CTA ${ctaParts.join(" ")} />` : `      <CTA />`);
  }

  void variants; // variants are baked into the component files themselves

  return `// Generated by HoltzUI
${imports.join("\n")}

export default function Page() {
  return (
    <main
      style={{
        backgroundColor: "var(--background)",
        color: "var(--foreground)",
        fontFamily: "var(--font-sans)",
      }}
    >
${usages.join("\n")}
    </main>
  );
}
`;
}

// ─── README ──────────────────────────────────────────────────────────────────

function generateReadme(brandName: string, sections: ProjectSections): string {
  const activeNames = (
    [
      sections.navbar       && "Navbar",
      sections.hero         && "Hero",
      sections.features     && "Features",
      sections.testimonials && "Testimonials",
      sections.pricing      && "Pricing",
      sections.cta          && "CTA",
    ] as (string | false)[]
  ).filter(Boolean) as string[];

  return `# ${brandName}

> Generated by [HoltzUI](https://holtz-ui.dev)

## Getting Started

\`\`\`bash
pnpm install
pnpm dev
\`\`\`

## Project Structure

\`\`\`
app/
  page.tsx           — main page (imports your sections)
  layout.tsx         — root layout
  globals.css        — CSS variable definitions
components/
  sections/
${activeNames.map((n) => `    ${n}.tsx`).join("\n")}
lib/
  tokens.ts          — design token values
package.json
\`\`\`

## Customization

- Edit \`app/globals.css\` to change colors, fonts, radius, and spacing.
- Edit \`lib/tokens.ts\` to reference token values in your own code.
- Each component in \`components/sections/\` is self-contained and uses CSS variables.

## Active Sections

${activeNames.map((n) => `- ${n}`).join("\n")}
`;
}

// ─── Main export ─────────────────────────────────────────────────────────────

const defaultVariants: ProjectVariants = {
  navbar: "default",
  hero: "centered",
  pricing: "cards",
  features: "grid",
  testimonials: "grid",
  cta: "centered",
};

export function generateProjectFiles(
  tokens: DesignTokens,
  sections: ProjectSections = { navbar: true, hero: true, features: true, testimonials: true, pricing: true, cta: true },
  brandName = "HoltzUI",
  variants: Partial<ProjectVariants> = {},
  heroContent?: { headline?: string; subheadline?: string; ctaLabel?: string },
  ctaContent?:  { heading?: string;  subheading?: string;  ctaLabel?: string },
): Record<string, string> {
  const v: ProjectVariants = { ...defaultVariants, ...variants };

  const files: Record<string, string> = {
    "app/page.tsx":       generatePageTsx(sections, v, brandName, heroContent, ctaContent),
    "app/layout.tsx":     generateLayoutTsx(tokens),
    "app/globals.css":    generateGlobalsCss(tokens),
    "lib/tokens.ts":      generateTokensTs(tokens),
    "package.json":       generatePackageJson(brandName),
    "next.config.ts":     generateNextConfig(),
    "postcss.config.mjs": generatePostcssConfig(),
    "tsconfig.json":      generateTsConfig(),
    "README.md":          generateReadme(brandName, sections),
  };

  if (sections.navbar)       files["components/sections/Navbar.tsx"]       = generateNavbarComponent(v.navbar, brandName);
  if (sections.hero)         files["components/sections/Hero.tsx"]         = generateHeroComponent(v.hero, brandName);
  if (sections.features)     files["components/sections/Features.tsx"]     = generateFeaturesComponent(v.features);
  if (sections.testimonials) files["components/sections/Testimonials.tsx"] = generateTestimonialsComponent(v.testimonials);
  if (sections.pricing)      files["components/sections/Pricing.tsx"]      = generatePricingComponent(v.pricing);
  if (sections.cta)          files["components/sections/CTA.tsx"]          = generateCTAComponent(v.cta);

  return files;
}
